name: Cypress Tests using Cypress Docker Image

on: push

jobs:
  cypress-run:
    runs-on: ubuntu-22.04
    container:
      image: cypress/base:latest
      options: --user 1001
    steps:
      - name: Install Cypress
        run: npm install cypress --save-dev
      - name: Run Cypress
        run: npx cypress run
